GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/info

###

GET http://localhost:3001/api/persons/2

### id not in data

GET http://localhost:3001/api/persons/-1

###

DELETE http://localhost:3001/api/persons/2

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Alan Turing",
    "number": "23-06-12070654"
}

### empty number

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Alan Turing",
    "number": ""
}

### empty name

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": "23-06-12070654"
}

### non-unique name

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "050-123456"
}